apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldstar-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goldstar-backend
  template:
    metadata:
      labels:
        app: goldstar-backend
    spec:
      containers:
      - name: backend
        image: goldstar-backend:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: goldstar-backend
spec:
  selector:
    app: goldstar-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldstar-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goldstar-frontend
  template:
    metadata:
      labels:
        app: goldstar-frontend
    spec:
      containers:
      - name: frontend
        image: goldstar-frontend:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: goldstar-frontend
spec:
  selector:
    app: goldstar-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
